id: ID6F38985
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-20T12:08:36+00:00'
last_modified: '2022-06-09T17:41:37.572209+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8900
  title: གསུང་འབུམ། ངག་དབང་ཆོས་གྲགས། ༼རྫོང་སར་ཁམས་བྱེའི་གློག་ཀླད་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DF92:
      image_group_id: I1KG8989
      title: Volume 1 of gsung 'bum/_ngag dbang chos grags/ (rdzong sar khams bye)
      total_pages: 602
      order: 1
      base_file: DF92.txt
    B983:
      image_group_id: I1KG8990
      title: Volume 2 of gsung 'bum/_ngag dbang chos grags/ (rdzong sar khams bye)
      total_pages: 604
      order: 2
      base_file: B983.txt
    '9358':
      image_group_id: I1KG8991
      title: Volume 3 of gsung 'bum/_ngag dbang chos grags/ (rdzong sar khams bye)
      total_pages: 722
      order: 3
      base_file: 9358.txt
    E4C9:
      image_group_id: I1KG8992
      title: Volume 4 of gsung 'bum/_ngag dbang chos grags/ (rdzong sar khams bye)
      total_pages: 672
      order: 4
      base_file: E4C9.txt
    4E75:
      image_group_id: I1KG8993
      title: Volume 5 of gsung 'bum/_ngag dbang chos grags/ (rdzong sar khams bye)
      total_pages: 566
      order: 5
      base_file: 4E75.txt
    '4022':
      image_group_id: I1KG8994
      title: Volume 6 of gsung 'bum/_ngag dbang chos grags/ (rdzong sar khams bye)
      total_pages: 660
      order: 6
      base_file: 4022.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
